INSERT_INTO_MOVIES_TABLE = '''
    INSERT INTO MOVIES(NAME, RATING)
    VALUES (?, ?)
'''

INSERT_INTO_PROJECTIONS_TABLE = '''
    INSERT INTO PROJECTIONS(MOVIE_ID, TYPE, PROJECTIONS_DATE, PROJECTIONS_TIME)
    VALUES (?, ?, ?, ?)
'''

INSERT_INTO_USERS_TABLE = '''
    INSERT INTO USERS(USERNAME, PASSWORD)
    VALUES (?, ?)
'''

INSERT_INTO_RESERVATIONS_TABLE = '''
    INSERT INTO RESERVATIONS(USER_ID, PROJECTION_ID, ROW, COL)
    VALUES (?, ?, ?, ?)
'''

SELECT_MOVIES_ORDERED_BY_RATING = '''
    SELECT *
    FROM MOVIES
    ORDER BY RATING;
'''

SELECT_PROJECTIONS_ORDERED_BY_DATE = '''
    SELECT PROJECTIONS.*, COUNT(RESERVATIONS.ROW * RESERVATIONS.COL)
    FROM PROJECTIONS
    LEFT JOIN RESERVATIONS
    ON RESERVATIONS.PROJECTION_ID = PROJECTIONS.ID
    WHERE PROJECTIONS.MOVIE_ID = ? AND PROJECTIONS.PROJECTIONS_DATE LIKE ?
    GROUP BY PROJECTIONS.ID
    ORDER BY PROJECTIONS.PROJECTIONS_DATE;
'''

IS_USER_IN_USERS = '''
    SELECT *
    FROM USERS
    WHERE USERNAME = ? and PASSWORD LIKE ?;
'''

SELECT_AVAILABLE_SEATS = '''
    SELECT ROW, COL
    FROM RESERVATIONS
    WHERE PROJECTION_ID = ? AND ROW IS NOT NULL AND COL IS NOT NULL;
'''
